package dal;
// Generated 6-jan-2015 14:41:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblCategorie generated by hbm2java
 */
public class Categorie  implements java.io.Serializable {


     private Integer id;
     private String naam;
     private Set tblVerzamelings = new HashSet(0);

    public Categorie() {
    }

	
    public Categorie(String naam) {
        this.naam = naam;
    }
    public Categorie(String naam, Set tblVerzamelings) {
       this.naam = naam;
       this.tblVerzamelings = tblVerzamelings;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public Set getTblVerzamelings() {
        return this.tblVerzamelings;
    }
    
    public void setTblVerzamelings(Set tblVerzamelings) {
        this.tblVerzamelings = tblVerzamelings;
    }




}


