package dal;
// Generated 6-jan-2015 14:41:51 by Hibernate Tools 4.3.1



/**
 * TblVerzameling generated by hbm2java
 */
public class Verzameling  implements java.io.Serializable {


     private Integer id;
     private Categorie tblCategorie;
     private VerzamelingsType tblType;
     private String naam;
     private String beschrijving;
     private boolean inBezit;
     private int categoryId;
     private int typeId;

    public Verzameling() {
    }

    public Verzameling(Categorie tblCategorie, VerzamelingsType tblType, String naam, String beschrijving, boolean inBezit) {
       this.tblCategorie = tblCategorie;
       this.tblType = tblType;
       this.naam = naam;
       this.beschrijving = beschrijving;
       this.inBezit = inBezit;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Categorie getTblCategorie() {
        return this.tblCategorie;
    }
    
    public void setTblCategorie(Categorie tblCategorie) {
        this.tblCategorie = tblCategorie;
    }
    public VerzamelingsType getTblType() {
        return this.tblType;
    }
    
    public void setTblType(VerzamelingsType tblType) {
        this.tblType = tblType;
    }
    public String getNaam() {
        return this.naam;
    }
    
    
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public String getBeschrijving() {
        return this.beschrijving;
    }
    
    public void setBeschrijving(String beschrijving) {
        this.beschrijving = beschrijving;
    }
    public boolean isInBezit() {
        return this.inBezit;
    }
    
    public void setInBezit(boolean inBezit) {
        this.inBezit = inBezit;
    }

    /**
     * @return the categoryId
     */
    public int getCategoryId() {
        return categoryId;
    }

    /**
     * @return the typeId
     */
    public int getTypeId() {
        return typeId;
    }

    /**
     * @param categoryId the categoryId to set
     */
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * @param typeId the typeId to set
     */
    public void setTypeId(int typeId) {
        this.typeId = typeId;
    }




}


